workspace:
  base: /go

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo
  docker:
    image: docker
    repo: plugins/drone-cloudfoundry
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: Cloud Foundry
  desc: Deploy or update a project on Cloud Foundry
  type: deploy
  image: plugins/drone-cloudfoundry
  labels:
    - paas
