pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-cloudfoundry
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Cloud Foundry
  desc: Deploy or update a project on Cloud Foundry
  type: deploy
  image: plugins/drone-cloudfoundry
  labels:
    - paas
